//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odyssey.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Info {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Info() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Odyssey.Properties.Info", typeof(Info).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating instance parameter: [{0}].
        /// </summary>
        public static string INFO_Graphics_InstanceParameterCreation {
            get {
                return ResourceManager.GetString("INFO_Graphics_InstanceParameterCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer [{0}] disposed: [{1}].
        /// </summary>
        public static string INFO_OE_BufferDisposed {
            get {
                return ResourceManager.GetString("INFO_OE_BufferDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DX11 device created.
        /// </summary>
        public static string INFO_OE_DeviceCreated {
            get {
                return ResourceManager.GetString("INFO_OE_DeviceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating device.
        /// </summary>
        public static string INFO_OE_DeviceCreating {
            get {
                return ResourceManager.GetString("INFO_OE_DeviceCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} disposed.
        /// </summary>
        public static string INFO_OE_Disposed {
            get {
                return ResourceManager.GetString("INFO_OE_Disposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} disposing.
        /// </summary>
        public static string INFO_OE_Disposing {
            get {
                return ResourceManager.GetString("INFO_OE_Disposing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odyssey engine started..
        /// </summary>
        public static string INFO_OE_Started {
            get {
                return ResourceManager.GetString("INFO_OE_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odyssey engine starting..
        /// </summary>
        public static string INFO_OE_Starting {
            get {
                return ResourceManager.GetString("INFO_OE_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying instance parameter: [{0}].[{1}].
        /// </summary>
        public static string INFO_Rendering_ApplyInstanceParameter {
            get {
                return ResourceManager.GetString("INFO_Rendering_ApplyInstanceParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying scene parameter: [{0}].[{1}].
        /// </summary>
        public static string INFO_Rendering_ApplySceneParameter {
            get {
                return ResourceManager.GetString("INFO_Rendering_ApplySceneParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture not cached.
        /// </summary>
        public static string RES_TextureNotCached {
            get {
                return ResourceManager.GetString("RES_TextureNotCached", resourceCulture);
            }
        }
    }
}
